name: Build binaries

on: workflow_call

env:
  UV_PYTHON: "3.13"

jobs:
  build:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux-x64
          - runner: ubuntu-24.04-arm
            platform: linux-arm64

          - runner: macos-15-intel
            platform: macos-x64
          - runner: macos-26
            platform: macos-arm64

          - runner: windows-latest
            platform: windows-x64
          - runner: windows-11-arm
            platform: windows-arm64
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install UPX on Windows
        if: runner.os == 'Windows'
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
        continue-on-error: true

      - name: Set PyInstaller --strip option on non-Windows
        id: strip
        if: runner.os != 'Windows'
        run: echo 'flag=--strip' >> $GITHUB_OUTPUT

      - name: Build with PyInstaller
        run: >
          uv run --no-dev --group bundle pyinstaller src/pyscribe/cli.py
          --onefile --name pyscribe --optimize 2 --icon NONE ${{ steps.strip.outputs.flag }}

      - name: Smoke test (bundle)
        shell: bash
        run: |
          PROJECT_VER=`uv version --short`
          RAW_BUNDLE_VER=`dist/pyscribe --version`
          BUNDLE_VER=${RAW_BUNDLE_VER#* }
          echo Project version: $PROJECT_VER
          echo Bundle version: $BUNDLE_VER
          [ "$PROJECT_VER" = "$BUNDLE_VER" ]

      - name: Archive binary
        shell: bash
        env:
          ARCHIVE_NAME: pyscribe-${{ matrix.platform }}
        run: |
          cd dist
          if [ ${{ runner.os }} = Windows ]; then
            7z a "../$ARCHIVE_NAME.zip" *
          else
            tar -cvzf "../$ARCHIVE_NAME.tar.gz" *
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.platform }}
          path: pyscribe-${{ matrix.platform }}.*
